all:
	pdflatex questionnaire.tex
	pdflatex questionnaire.tex
	pdflatex questionnaire-simple.tex
	pdflatex questionnaire-simple.tex

clean:
	rm -f *.toc *.aux *.ps *.log *.lof *.bbl *.blg *.hix *.tid *.tde *.out *~

